# Generated by Django 4.0.6 on 2022-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('features', models.TextField(verbose_name='Features')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('stockNum', models.IntegerField(verbose_name='Stock Number')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('family', models.CharField(max_length=100, verbose_name='Family')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('limited', models.BooleanField(default=False, verbose_name='Limited')),
                ('water_resistance_depth', models.IntegerField(default=0, verbose_name='Water Resistance Feature')),
                ('case_description', models.TextField(verbose_name='Case Description')),
                ('dial_description', models.TextField(verbose_name='Dial Description')),
                ('movement_description', models.TextField(verbose_name='Movement Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
