# Generated by Django 3.2.14 on 2022-07-28 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trasia_watches_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='image',
        ),
        migrations.AddField(
            model_name='watch',
            name='users',
            field=models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WatchesPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasia_watches_store.watch')),
            ],
        ),
    ]
