# Generated by Django 3.2.14 on 2022-07-29 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trasia_watches_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='users',
            field=models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
