# Generated by Django 4.0.6 on 2022-07-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='case_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='dial_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='family',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='features',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='limited',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='model',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='movement_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='stockNum',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='water_resistance_depth',
        ),
    ]
