# Generated by Django 3.2.14 on 2022-08-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_description',
            field=models.TextField(blank=True, null=True, verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='dial_description',
            field=models.TextField(blank=True, null=True, verbose_name='Dial Description'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='limited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Limited'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement_description',
            field=models.TextField(blank=True, null=True, verbose_name='Movement Description'),
        ),
    ]
