# Generated by Django 3.2.14 on 2022-08-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0003_auto_20220802_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='stockNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Number'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='water_resistance_depth',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Water Resistance Feature'),
        ),
    ]
