# Generated by Django 3.2.14 on 2022-08-02 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0004_auto_20220802_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='productCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
