# Generated by Django 3.2.14 on 2022-08-03 11:39

from django.db import migrations, models
import trasia_watches_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0005_watch_productcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchespicture',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=trasia_watches_store.models.upload_to, verbose_name='Photos'),
        ),
    ]
