# Generated by Django 3.2.14 on 2022-08-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0006_alter_watchespicture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchespicture',
            old_name='url',
            new_name='image',
        ),
    ]
