# Generated by Django 3.2.14 on 2022-12-11 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trasia_watches_store', '0007_rename_url_watchespicture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='case_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='dial_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='family',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='features',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='limited',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='model',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='movement_description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='productCode',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='stockNum',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='water_resistance_depth',
        ),
        migrations.RemoveField(
            model_name='watchespicture',
            name='image',
        ),
        migrations.AddField(
            model_name='watchespicture',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='wimage',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
