databases:
  - name: trasiastore
    databaseName: trasiastore
    user: trasiastore

services:
  - type: web
    name: twsbe
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn twsbe.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trasiastore
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4